name: walking
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  audio_service: ^0.18.17
  dchs_motion_sensors: ^1.1.0
  flutter:
    sdk: flutter
  flutter_foreground_task: ^8.17.0
  flutter_launcher_icons: ^0.14.3
  just_audio: ^0.9.46
  pedometer: ^4.0.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  image_path_android: "assets/logo.png"
  android: true

flutter:
  uses-material-design: true

  assets:
    - assets/step.mp3
