name: walking
description: "A new Flutter project."
publish_to: "none"
version: 0.1.1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  audio_service: ^0.18.17
  dchs_motion_sensors: ^1.1.0
  flutter:
    sdk: flutter
  flutter_foreground_task: ^8.17.0
  flutter_launcher_icons: ^0.14.3
  gif: ^2.3.0
  just_audio: ^0.9.46
  package_info_plus: ^8.3.0
  pedometer: ^4.0.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  image_path_android: "assets/icon.jpg"
  adaptive_icon_background: "#f785ff"
  android: true

flutter:
  uses-material-design: true

  assets:
    - assets/fish.png
    - assets/spinning_fish.gif

    - assets/sounds/cans.wav
    - assets/sounds/coat.wav
    - assets/sounds/crab.wav
    - assets/sounds/im_walking.wav
    - assets/sounds/loud_snow.wav
    - assets/sounds/loud_water.wav
    - assets/sounds/snow.wav
    - assets/sounds/water.wav
    - assets/sounds/step.mp3
    - assets/sounds/step_quick.mp3
